import assert from "node:assert/strict";
import { CompanionManager } from "../src/core/companion.mjs";

const m=new CompanionManager();
const c=m.create({name:"Nova",mode:"romantic",persona:"warm, witty, affectionate"});
assert.equal(c.media.chat,true);
m.setPreference(c.id,"favoriteTopic","movies");
m.setBoundary(c.id,"noVideo",false);
m.updateRelationship(c.id,{stage:"romantic",affection:"high",trust:72});
assert.equal(c.relationship.trust,72);
const memory=m.remember(c.id,{content:"Our first date night",tags:["date-night"],importance:.9});
assert.equal(m.memories(c.id)[0].id,memory.id);
const s=m.startSession(c.id,"video");
assert.equal(s.active,true);
m.addMessage(s.id,{role:"user",content:"Hello"});
m.addMessage(s.id,{role:"assistant",content:"Hey — good to see you."});
assert.equal(m.listMessages(s.id).length,2);
assert.equal(m.endSession(s.id).active,false);
m.setMedia(c.id,"voice",false);
assert.throws(()=>m.startSession(c.id,"voice"),/Media disabled/);
const snap=m.snapshot(); const restored=new CompanionManager().restore(snap);
assert.equal(restored.listMessages(s.id).length,2);
console.log("companion ok");
