import assert from "node:assert/strict";
import { IntimacyManager } from "../src/core/intimacy.mjs";
const m=new IntimacyManager();
const p=m.create({affection:"devoted",dateMode:"late-night-chat",warmth:95});
assert.equal(p.warmth,95);
const moment=m.addMoment(p.id,{text:"Remember our favorite movie",tags:["movie"]});
assert.equal(m.momentsFor(p.id)[0].id,moment.id);
const d=m.startDateNight(p.id,{title:"Tonight Together"});
assert.equal(d.active,true);
m.endDateNight(d.id);
assert.equal(d.active,false);
assert.throws(()=>m.create({dateMode:"invalid"}),/Unknown date mode/);
console.log("intimacy ok");
