export const MAJOR_BIBLICAL_CHARACTERS = Object.freeze([
  {canonicalName:"Adam",aliases:["Adam"],primaryStories:["Creation","Fall"],relationships:["Eve — wife","Cain — son","Abel — son","Seth — son"],keyTraits:["first man","cultivator","fallen"],notes:"Humanity's first man in Genesis.",scriptureReferences:["Genesis 2:7-25","Genesis 3:1-24","Genesis 5:1-5"]},
  {canonicalName:"Eve",aliases:["Eve"],primaryStories:["Creation","Fall"],relationships:["Adam — husband","Cain — son","Abel — son","Seth — son"],keyTraits:["first woman","mother of humanity"],notes:"The first woman, formed as Adam's counterpart.",scriptureReferences:["Genesis 2:18-25","Genesis 3:1-24","Genesis 4:1-2"]},
  {canonicalName:"Noah",aliases:["Noah"],primaryStories:["The Flood","Covenant with Noah"],relationships:["Shem — son","Ham — son","Japheth — son","Naamah — wife"],keyTraits:["righteous","builder","obedient"],notes:"Built the ark and survived the Flood.",scriptureReferences:["Genesis 6:9-22","Genesis 7:1-24","Genesis 8:1-22","Genesis 9:1-29"]},
  {canonicalName:"Abraham",aliases:["Abram"],primaryStories:["Call of Abraham","Covenant","Isaac"],relationships:["Sarah — wife","Isaac — son","Ishmael — son","Lot — nephew"],keyTraits:["patriarch","faithful","covenant"],notes:"Patriarch through whom God promises blessing to the nations.",scriptureReferences:["Genesis 12:1-9","Genesis 15:1-21","Genesis 17:1-27","Genesis 22:1-19"]},
  {canonicalName:"Sarah",aliases:["Sarai"],primaryStories:["Abraham and Sarah","Birth of Isaac"],relationships:["Abraham — husband","Isaac — son","Hagar — household servant"],keyTraits:["matriarch","faithful","mother"],notes:"Wife of Abraham and mother of Isaac.",scriptureReferences:["Genesis 12:10-20","Genesis 18:1-15","Genesis 21:1-21"]},
  {canonicalName:"Isaac",aliases:["Isaac"],primaryStories:["Binding of Isaac","Jacob and Esau"],relationships:["Abraham — father","Sarah — mother","Rebekah — wife","Jacob — son","Esau — son"],keyTraits:["patriarch","covenant heir"],notes:"Son of Abraham and Sarah.",scriptureReferences:["Genesis 21:1-7","Genesis 22:1-19","Genesis 24:62-67","Genesis 27:1-40"]},
  {canonicalName:"Jacob",aliases:["Israel"],primaryStories:["Jacob and Esau","Joseph"],relationships:["Isaac — father","Rebekah — mother","Rachel — wife","Leah — wife","Joseph — son"],keyTraits:["patriarch","struggler","father of tribes"],notes:"Renamed Israel; father of the twelve tribal ancestors.",scriptureReferences:["Genesis 25:19-34","Genesis 28:10-22","Genesis 32:22-32","Genesis 35:9-15"]},
  {canonicalName:"Joseph",aliases:["Joseph"],primaryStories:["Joseph in Egypt"],relationships:["Jacob — father","Rachel — mother","Benjamin — brother","Potiphar — master"],keyTraits:["dreamer","administrator","forgiving"],notes:"Jacob's son who rose to authority in Egypt.",scriptureReferences:["Genesis 37:1-36","Genesis 39:1-23","Genesis 41:37-57","Genesis 45:1-15"]},
  {canonicalName:"Moses",aliases:["Moses"],primaryStories:["Exodus","Wilderness","Law at Sinai"],relationships:["Aaron — brother","Miriam — sister","Zipporah — wife","Joshua — successor"],keyTraits:["prophet","deliverer","lawgiver","leader"],notes:"Led Israel out of Egypt and received the covenant law at Sinai.",scriptureReferences:["Exodus 2:1-25","Exodus 3:1-22","Exodus 14:1-31","Exodus 20:1-21"]},
  {canonicalName:"Aaron",aliases:["Aaron"],primaryStories:["Exodus","Priesthood"],relationships:["Moses — brother","Miriam — sister","Moses — leader"],keyTraits:["priest","spokesman","brother"],notes:"Moses' brother and Israel's first high priest.",scriptureReferences:["Exodus 4:14-16","Exodus 28:1-43","Leviticus 8:1-36"]},
  {canonicalName:"Miriam",aliases:["Miriam"],primaryStories:["Exodus","Wilderness"],relationships:["Moses — brother","Aaron — brother"],keyTraits:["prophetess","worship leader","sister"],notes:"Prophetess and sister of Moses and Aaron.",scriptureReferences:["Exodus 2:1-10","Exodus 15:20-21","Numbers 12:1-15"]},
  {canonicalName:"Joshua",aliases:["Joshua son of Nun"],primaryStories:["Conquest of Canaan"],relationships:["Moses — predecessor","Caleb — fellow scout"],keyTraits:["leader","warrior","faithful"],notes:"Moses' successor who led Israel into Canaan.",scriptureReferences:["Numbers 27:18-23","Joshua 1:1-18","Joshua 6:1-27","Joshua 24:1-28"]},
  {canonicalName:"Rahab",aliases:["Rahab"],primaryStories:["Jericho"],relationships:["Joshua — opposing commander"],keyTraits:["courageous","protective","faithful"],notes:"Woman of Jericho who protected Israelite spies.",scriptureReferences:["Joshua 2:1-24","Joshua 6:22-25"]},
  {canonicalName:"Ruth",aliases:["Ruth the Moabite"],primaryStories:["Ruth"],relationships:["Naomi — mother-in-law","Boaz — husband"],keyTraits:["loyal","devoted","Moabite"],notes:"Moabite woman whose loyalty to Naomi leads into Israel's royal lineage.",scriptureReferences:["Ruth 1:1-22","Ruth 2:1-23","Ruth 4:1-22"]},
  {canonicalName:"Samuel",aliases:["Samuel"],primaryStories:["Samuel","Saul","David"],relationships:["Hannah — mother","Saul — anointed king","David — anointed king"],keyTraits:["prophet","judge","seer"],notes:"Prophet and judge who anointed Israel's first two kings.",scriptureReferences:["1 Samuel 1:1-28","1 Samuel 3:1-21","1 Samuel 10:1-24","1 Samuel 16:1-13"]},
  {canonicalName:"Saul",aliases:["Saul son of Kish"],primaryStories:["Saul's reign","David and Saul"],relationships:["Samuel — prophet","Jonathan — son","David — rival"],keyTraits:["first king","warrior","troubled"],notes:"Israel's first king.",scriptureReferences:["1 Samuel 9:1-27","1 Samuel 10:1-27","1 Samuel 18:1-30","1 Samuel 31:1-13"]},
  {canonicalName:"David",aliases:["David son of Jesse"],primaryStories:["David and Goliath","David's reign"],relationships:["Jesse — father","Jonathan — friend","Saul — predecessor","Bathsheba — wife","Solomon — son"],keyTraits:["king","warrior","psalmist","repentant"],notes:"King of Israel and ancestor of Jesus according to the New Testament.",scriptureReferences:["1 Samuel 16:1-13","1 Samuel 17:1-58","2 Samuel 5:1-5","2 Samuel 12:1-25"]},
  {canonicalName:"Solomon",aliases:["Solomon"],primaryStories:["Solomon's reign","Temple"],relationships:["David — father","Bathsheba — mother","Rehoboam — son"],keyTraits:["king","wise","builder"],notes:"David's son who built the temple in Jerusalem.",scriptureReferences:["1 Kings 3:1-28","1 Kings 6:1-38","1 Kings 8:1-66"]},
  {canonicalName:"Elijah",aliases:["Elijah the Tishbite"],primaryStories:["Elijah and Ahab","Mount Carmel"],relationships:["Ahab — king","Elisha — successor"],keyTraits:["prophet","zealous","miracle worker"],notes:"Prophet who confronted Ahab and the prophets of Baal.",scriptureReferences:["1 Kings 17:1-24","1 Kings 18:1-46","1 Kings 19:1-21"]},
  {canonicalName:"Esther",aliases:["Hadassah","Esther"],primaryStories:["Esther"],relationships:["Mordecai — cousin/guardian","Ahasuerus — husband"],keyTraits:["queen","courageous","intercessor"],notes:"Jewish queen who risked her life to protect her people.",scriptureReferences:["Esther 2:5-20","Esther 4:1-17","Esther 7:1-10","Esther 8:1-17"]},
  {canonicalName:"Job",aliases:["Job"],primaryStories:["Job"],relationships:["Job's wife — wife","Eliphaz — friend","Bildad — friend","Zophar — friend"],keyTraits:["suffering","faithful","persevering"],notes:"Righteous man tested through severe suffering.",scriptureReferences:["Job 1:1-22","Job 2:1-13","Job 38:1-42:17"]},
  {canonicalName:"Isaiah",aliases:["Isaiah son of Amoz"],primaryStories:["Isaiah"],relationships:["Hezekiah — king contemporary"],keyTraits:["prophet","visionary"],notes:"Major prophet whose book contains messianic and servant prophecies.",scriptureReferences:["Isaiah 1:1","Isaiah 6:1-13","Isaiah 9:1-7","Isaiah 53:1-12"]},
  {canonicalName:"Jeremiah",aliases:["Jeremiah son of Hilkiah"],primaryStories:["Jeremiah"],relationships:["Baruch — scribe"],keyTraits:["prophet","lamenter","watchman"],notes:"Prophet who warned Judah before and during the fall of Jerusalem.",scriptureReferences:["Jeremiah 1:1-19","Jeremiah 7:1-34","Jeremiah 20:7-18","Jeremiah 32:1-44"]},
  {canonicalName:"Daniel",aliases:["Daniel"],primaryStories:["Exile","Daniel in Babylon"],relationships:["Hananiah — companion","Mishael — companion","Azariah — companion"],keyTraits:["prophet","wise","faithful"],notes:"Exile-era servant of God known for wisdom and visions.",scriptureReferences:["Daniel 1:1-21","Daniel 2:1-49","Daniel 6:1-28","Daniel 7:1-28"]},
  {canonicalName:"John the Baptist",aliases:["John","John the Baptizer"],primaryStories:["Preparation for Jesus","Baptism of Jesus"],relationships:["Zechariah — father","Elizabeth — mother","Jesus — relative and Messiah"],keyTraits:["prophet","forerunner","preacher"],notes:"Prophet who prepared the way for Jesus and baptized him.",scriptureReferences:["Matthew 3:1-17","Mark 1:1-11","Luke 1:5-25","John 1:19-34"]},
  {canonicalName:"Jesus",aliases:["Jesus of Nazareth","Christ","Messiah","Son of God","Son of Man"],primaryStories:["Gospels","Crucifixion","Resurrection"],relationships:["Mary — mother","Joseph — legal father","Peter — disciple","John — disciple"],keyTraits:["Messiah","teacher","healer","crucified and risen"],notes:"Central figure of the New Testament.",scriptureReferences:["Matthew 1:18-25","Mark 1:1-45","Luke 2:1-52","John 1:1-18","Matthew 27:1-66","Matthew 28:1-20"]},
  {canonicalName:"Mary",aliases:["Mary mother of Jesus","Virgin Mary"],primaryStories:["Annunciation","Birth of Jesus","Crucifixion"],relationships:["Jesus — son","Joseph — husband"],keyTraits:["mother","faithful","disciple"],notes:"Mother of Jesus.",scriptureReferences:["Luke 1:26-56","Luke 2:1-52","John 2:1-12","John 19:25-27"]},
  {canonicalName:"Peter",aliases:["Simon Peter","Simon"],primaryStories:["Gospels","Pentecost","Early Church"],relationships:["Jesus — teacher","Andrew — brother","Paul — fellow apostle"],keyTraits:["apostle","fisherman","leader","restored"],notes:"One of Jesus' Twelve and a leading figure in Acts.",scriptureReferences:["Matthew 4:18-22","Matthew 16:13-20","John 21:1-19","Acts 2:1-41"]},
  {canonicalName:"John",aliases:["John son of Zebedee","John the Apostle"],primaryStories:["Gospels","Early Church"],relationships:["James — brother","Zebedee — father","Jesus — teacher"],keyTraits:["apostle","disciple","witness"],notes:"Apostle and prominent witness in the Gospel tradition.",scriptureReferences:["Mark 1:16-20","John 13:21-30","John 19:25-27","Acts 3:1-11"]},
  {canonicalName:"Paul",aliases:["Saul of Tarsus","Paul the Apostle"],primaryStories:["Conversion of Saul","Missionary Journeys","Epistles"],relationships:["Barnabas — missionary partner","Silas — missionary partner","Timothy — coworker"],keyTraits:["apostle","missionary","teacher"],notes:"Apostle to the Gentiles and author associated with numerous New Testament letters.",scriptureReferences:["Acts 9:1-31","Acts 13:1-14:28","Acts 16:1-40","Acts 28:16-31"]},
  {canonicalName:"Mary Magdalene",aliases:["Mary Magdalene"],primaryStories:["Ministry of Jesus","Crucifixion","Resurrection"],relationships:["Jesus — teacher"],keyTraits:["disciple","witness","faithful"],notes:"Disciple and witness to Jesus' death and resurrection.",scriptureReferences:["Luke 8:1-3","John 19:25","John 20:1-18"]},
  {canonicalName:"Lazarus",aliases:["Lazarus of Bethany"],primaryStories:["Raising of Lazarus"],relationships:["Martha — sister","Mary of Bethany — sister","Jesus — friend"],keyTraits:["friend of Jesus","raised from death"],notes:"Man from Bethany whom Jesus raised from the dead.",scriptureReferences:["John 11:1-44","John 12:1-11"]},
  {canonicalName:"Martha",aliases:["Martha of Bethany"],primaryStories:["Bethany","Raising of Lazarus"],relationships:["Mary of Bethany — sister","Lazarus — brother","Jesus — friend"],keyTraits:["host","confessing faith","practical"],notes:"Sister of Lazarus and Mary of Bethany.",scriptureReferences:["Luke 10:38-42","John 11:1-44","John 12:1-8"]}
]);

export function seedMajorCharacters(store) {
  if (store.list().length > 0) return false;
  for (const character of MAJOR_BIBLICAL_CHARACTERS) store.create(character);
  return true;
}
