import crypto from "node:crypto";import fs from "node:fs";import path from "node:path";import {promisify} from "node:util";
const scrypt=promisify(crypto.scrypt),sessions=new Map(),fails=new Map(),LOOPBACK=new Set(["127.0.0.1","::1","::ffff:127.0.0.1"]),EXEMPT=new Set(["/owner-login","/owner-logout","/api/health","/sw.js","/manifest.webmanifest"]);
const file=()=>path.resolve(process.env.APEX_AUTH_FILE||"./.apex_auth/owner.json"),digest=v=>crypto.createHash("sha256").update(String(v)).digest(),same=(a,b)=>crypto.timingSafeEqual(digest(a),digest(b)),ip=r=>String(r.headers["x-forwarded-for"]||r.socket.remoteAddress||"").split(",")[0].trim(),idle=()=>{const n=Number(process.env.APEX_IDLE_MINUTES??30);return Number.isFinite(n)&&n>=0?n*60000:1800000};
let cache;function auth(){if(cache!==undefined)return cache;try{cache=JSON.parse(fs.readFileSync(file(),"utf8"))}catch{cache=null}return cache}function save(a){const f=file(),t=f+"."+process.pid+".tmp";fs.mkdirSync(path.dirname(f),{recursive:true,mode:0o700});fs.writeFileSync(t,JSON.stringify(a),{mode:0o600});fs.renameSync(t,f);cache=a}
function cookie(r){const x=(r.headers.cookie||"").split(";").map(v=>v.trim()).find(v=>v.startsWith("apex_session="));return x?x.slice(13):""}function origin(r){if(process.env.APEX_ORIGIN)return process.env.APEX_ORIGIN.replace(/\/$/,"");const p=String(r.headers["x-forwarded-proto"]||(r.secure?"https":"http")).split(",")[0],h=String(r.headers["x-forwarded-host"]||r.headers.host||"").split(",")[0];return p+"://"+h}
function owner(r){if(LOOPBACK.has(r.socket.remoteAddress)&&!r.headers["x-forwarded-for"]&&process.env.APEX_REQUIRE_LOGIN_LOCAL!=="true")return true;const s=sessions.get(cookie(r));if(!s)return false;const i=idle();if(i&&Date.now()-s.last>i){sessions.delete(cookie(r));return false}s.last=Date.now();return true}
function start(r,res){const sid=crypto.randomBytes(32).toString("hex");sessions.set(sid,{last:Date.now()});const sec=origin(r).startsWith("https")?"; Secure":"";res.setHeader("Set-Cookie",`apex_session=${sid}; Path=/; HttpOnly; SameSite=Strict${sec}; Max-Age=31536000`)}
const blocked=k=>{const f=fails.get(k);return f&&f.until>Date.now()&&f.n>=5},fail=k=>{const f=fails.get(k),n=f&&f.until>Date.now()?f.n+1:1;fails.set(k,{n,until:Date.now()+600000})};
export function ownerGate(req,res,next){if(EXEMPT.has(req.path)||req.path.startsWith("/owner/"))return next();if(owner(req)){req.apexOwner=true;return next()}if(req.path.startsWith("/api"))return res.status(401).json({error:"Owner only"});res.redirect("/owner-login")}
const page=(res,title,body)=>{res.setHeader("Cache-Control","no-store");res.type("html").send(`<!doctype html><meta name=viewport content="width=device-width,initial-scale=1"><title>${title}</title><style>body{font-family:system-ui;background:#0d1117;color:#eee;display:grid;place-items:center;min-height:100vh}main{width:min(360px,90vw);display:grid;gap:12px}input,button{padding:14px;font-size:17px;border-radius:8px;border:1px solid #444;background:#161b22;color:#eee}button{background:#238636;color:#fff}a{color:#58a6ff}</style><main>${body}</main>`)}
export function mountOwnerAuth(app){
 app.get("/owner/state",(req,res)=>{const a=auth();res.json({setup:!!a,enabled:!!process.env.APEX_COMMANDER_TOKEN,passkeys:!!a?.passkeys?.length,passkeyCount:a?.passkeys?.length||0})});
 app.get("/owner-login",(req,res)=>page(res,"Apex Login",`<h2>Apex Studio</h2><form method="post" action="/owner/login"><input name=password type=password placeholder="Password" minlength="10" required><button>Log in</button></form><p id=m></p>`));
 app.get("/owner-security",(req,res)=>owner(req)?page(res,"Security",`<h2>Security</h2><p>Password authentication is enabled. WebAuthn/Face ID registration can be added without changing the owner gate.</p><a href="/">Back to app</a> · <a href="/owner-logout">Log out</a>`):res.redirect("/owner-login"));
 app.get("/owner-logout",(req,res)=>{sessions.delete(cookie(req));res.setHeader("Set-Cookie","apex_session=; Path=/; Max-Age=0; HttpOnly; SameSite=Strict");res.redirect("/owner-login")});
 app.post("/owner/setup",expressJson(),async(req,res)=>{const a=auth(),who=ip(req),token=process.env.APEX_COMMANDER_TOKEN;if(a)return res.status(409).json({error:"Already set up"});if(!token||token==="change-me")return res.status(503).json({error:"Set APEX_COMMANDER_TOKEN first"});if(blocked(who))return res.status(429).json({error:"Too many tries"});if(!same(token,req.body?.code)){fail(who);return res.status(401).json({error:"Wrong setup code"})}const p=req.body?.password;if(typeof p!=="string"||p.length<10||p.length>200)return res.status(400).json({error:"Password must be 10 to 200 characters"});const salt=crypto.randomBytes(16),hash=await scrypt(p,salt,64,{N:32768,r:8,p:1,maxmem:128*1024*1024});save({password:{salt:salt.toString("base64url"),hash:hash.toString("base64url")},passkeys:[]});start(req,res);res.json({ok:true})});
 app.post("/owner/login",expressJson(),async(req,res)=>{const a=auth(),who=ip(req);if(!a)return res.status(409).json({error:"Not set up"});if(blocked(who))return res.status(429).json({error:"Too many tries"});const got=typeof req.body?.password==="string"?await scrypt(req.body.password,Buffer.from(a.password.salt,"base64url"),64,{N:32768,r:8,p:1,maxmem:128*1024*1024}):Buffer.alloc(0);if(!got.length||!crypto.timingSafeEqual(got,Buffer.from(a.password.hash,"base64url"))){fail(who);return res.status(401).json({error:"Wrong password"})}fails.delete(who);start(req,res);res.redirect("/")});
}
function expressJson(){return (req,res,next)=>{let b="";req.on("data",c=>{b+=c;if(b.length>100000)return req.destroy()});req.on("end",()=>{try{req.body=b?JSON.parse(b):{}}catch{return res.status(400).json({error:"Invalid JSON"})}next()})}}
export const skipForOwner=mw=>(req,res,next)=>req.apexOwner?next():mw(req,res,next);