import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import oracleRoute from "./routes/oracle.mjs";
import forgeRoute from "./routes/forge.mjs";
import bardRoute from "./routes/bard.mjs";
import { bootstrap } from "./src/runtime/bootstrap.mjs";
import { createApi } from "./src/api/routes.mjs";
import { requestId, securityHeaders, limitQuery, errorHandler } from "./src/api/middleware.mjs";
const __filename=fileURLToPath(import.meta.url), __dirname=path.dirname(__filename);
const app=express();
const studio=bootstrap();
await studio.load();
app.disable("x-powered-by");
app.use(requestId);
app.use(securityHeaders);
app.use(express.json({limit:"2mb",strict:true}));
app.use(express.static(path.join(__dirname,"public")));
app.get("/manifest.webmanifest",(req,res)=>res.sendFile(path.join(__dirname,"public","manifest.webmanifest")));
app.get("/sw.js",(req,res)=>res.sendFile(path.join(__dirname,"public","sw.js")));
app.get("/api/health",(req,res)=>res.json({ok:true,studio:"Apex Studio",version:studio.version,localOnly:studio.privacy.localOnly}));
app.use("/api/studio",limitQuery,createApi(studio));
app.use("/api/oracle",oracleRoute(studio));
app.use("/api/forge",forgeRoute(studio));
app.use("/api/bard",bardRoute(studio));
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
app.use(errorHandler);
const PORT=process.env.PORT||3000;
const HOST=process.env.APEX_BIND_HOST||(process.env.RAILWAY_ENVIRONMENT?"0.0.0.0":"127.0.0.1");
app.listen(PORT,HOST,()=>console.log("Apex Studio "+studio.version+" online on "+HOST+":"+PORT));
