import express from "express";
import net from "node:net";
import path from "path";
import { fileURLToPath } from "url";
import oracleRoute from "./routes/oracle.mjs";
import forgeRoute from "./routes/forge.mjs";
import bardRoute from "./routes/bard.mjs";
import { bootstrap } from "./src/runtime/bootstrap.mjs";
import { createApi } from "./src/api/routes.mjs";
import { requestId, securityHeaders, limitQuery, errorHandler } from "./src/api/middleware.mjs";
import { apexRouterGate } from "./routes-security.mjs";
import { ownerGate, mountOwnerAuth } from "./owner.mjs";
import { uploadRoute } from "./upload.mjs";
import { enforceApexPolicy } from "./apex_policy.mjs";

const __filename=fileURLToPath(import.meta.url), __dirname=path.dirname(__filename);
enforceApexPolicy();
const app=express();
const studio=bootstrap();
await studio.load();
await studio.omniStore.init();
app.disable("x-powered-by");
const lanOnly=process.env.APEX_LAN_ONLY!=="false";
app.use((req,res,next)=>{if(!lanOnly)return next();let ip=req.socket.remoteAddress||"";if(ip.startsWith("::ffff:"))ip=ip.slice(7);const privateV4=/^(10\\.|192\\.168\\.|172\\.(1[6-9]|2\\d|3[0-1])\\.|169\\.254\\.)/.test(ip);const privateV6=/^(::1$|fc|fd|fe80:)/i.test(ip);if(net.isIP(ip)&&!(privateV4||privateV6))return res.status(403).json({error:"LAN-only access policy denied"});next();});
app.use(requestId);
app.use(securityHeaders);
app.use(express.json({limit:"10mb",strict:true}));
app.get("/api/health",(req,res)=>res.json({ok:true,studio:"Apex Studio",version:studio.version,localOnly:studio.privacy.localOnly}));
mountOwnerAuth(app);
app.use(ownerGate);
app.use(express.static(path.join(__dirname,"public")));
app.get("/manifest.webmanifest",(req,res)=>res.sendFile(path.join(__dirname,"public","manifest.webmanifest")));
app.get("/sw.js",(req,res)=>res.sendFile(path.join(__dirname,"public","sw.js")));
app.post("/api/upload/:name",uploadRoute);
app.use("/api/studio",apexRouterGate,limitQuery,createApi(studio));
app.use("/api/oracle",apexRouterGate,oracleRoute(studio));
app.use("/api/forge",apexRouterGate,forgeRoute(studio));
app.use("/api/bard",apexRouterGate,bardRoute(studio));
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
app.use(errorHandler);
const PORT=process.env.PORT||3010;
const HOST=process.env.APEX_BIND_HOST??"0.0.0.0";
app.listen(PORT,HOST,()=>console.log("Apex Studio "+studio.version+" online on "+HOST+":"+PORT));
