import { KnowledgeGraph } from "../core/knowledge-graph.mjs";
import { ContinuityLedger } from "../core/continuity.mjs";
import { TimelineEngine } from "../core/timeline.mjs";
import { ProductionGraph } from "../core/production.mjs";
import { AgentOrchestrator } from "../agents/orchestrator.mjs";
import { AgentRegistry } from "../agents/registry.mjs";
import { ProjectStore } from "../core/project.mjs";
import { MemoryStore } from "../core/memory.mjs";
import { AssetRegistry } from "../assets/lineage.mjs";
import { WorldState } from "../world/state.mjs";
import { EventBus } from "../core/event-bus.mjs";
import { UniverseScale } from "../core/universe.mjs";
import { JobQueue } from "../core/jobs.mjs";
import { ProviderRegistry } from "../core/provider.mjs";
import { ToolRegistry } from "../agents/tool-registry.mjs";
import { SessionManager } from "./session.mjs";
import { createScene } from "../core/scene.mjs";
import { JsonStore } from "../core/persistence.mjs";
import { CommandLog } from "../core/undo.mjs";
import { universalSearch } from "../core/search.mjs";
import { Metrics } from "./observability.mjs";
import { KnowledgeBase } from "../core/knowledge-base.mjs";
import { RenderQueue } from "../core/render.mjs";
import { ReleaseManager } from "../core/release.mjs";
import { CollaborationLog } from "../core/collaboration.mjs";
import { EmbeddingIndex } from "../core/embedding.mjs";
import { CharacterStore } from "../characters/store.mjs";
import { SourceRegistry } from "../core/sources.mjs";
import { CommandRouter } from "../core/command-router.mjs";
export function createStudio(){
 const events=new EventBus();
 const studio={version:"5.0.0",events,projects:new ProjectStore(),memory:new MemoryStore(),graph:new KnowledgeGraph(),continuity:new ContinuityLedger(),timelines:new TimelineEngine(),production:new ProductionGraph(),agents:new AgentRegistry(),characters:new CharacterStore(),sources:new SourceRegistry(),commandsRouter:new CommandRouter(),knowledgeBase:new KnowledgeBase(),render:new RenderQueue(),releases:new ReleaseManager(),collaboration:new CollaborationLog(),embeddings:new EmbeddingIndex(),orchestrator:new AgentOrchestrator(),assets:new AssetRegistry(),world:new WorldState(),universe:new UniverseScale(),jobs:new JobQueue(events),providers:new ProviderRegistry(),tools:new ToolRegistry(),sessions:new SessionManager(),persistence:new JsonStore(),commands:new CommandLog(),metrics:new Metrics(),scenes:new Map()};
 studio.universe.seedMilkyWay();
 studio.createScene=input=>{const s=createScene(input);studio.scenes.set(s.id,s);events.emit("scene.created",s);return s;};
 studio.getScene=id=>studio.scenes.get(id)??null;
 studio.listScenes=()=>[...studio.scenes.values()];
 studio.snapshot=()=>({projects:studio.projects.list(),memories:studio.memory.items,agents:studio.agents.list(),assets:[...studio.assets.assets.values()],world:studio.world.snapshot(),universe:studio.universe.list(),scenes:studio.listScenes(),jobs:studio.jobs.list(),graph:studio.graph.snapshot(),characters:studio.characters.list(),sources:studio.sources.list(),documents:studio.knowledgeBase.list(),renders:studio.render.list(),releases:studio.releases.list(),collaboration:studio.collaboration.list()});
 studio.search=(query,limit=30)=>universalSearch(query,[{type:"projects",items:studio.projects.list()},{type:"memories",items:studio.memory.items},{type:"assets",items:[...studio.assets.assets.values()]},{type:"scenes",items:studio.listScenes()},{type:"universe",items:studio.universe.list()}],limit);
 studio.restore=()=>studio;
 events.on("asset.created",a=>studio.memory.remember({type:"asset",projectId:a.projectId,content:a.name,importance:.4}));
 studio.jobs.register("memory.remember",p=>studio.memory.remember(p));
 return studio;
}
