export const SETTINGS=['INT','EXT'];
export const TIMES_OF_DAY=['DAWN','DAY','DUSK','NIGHT','UNSPECIFIED'];
export const CHARACTER_ROLES=['speaking','silent','background'];
export const INFERABLE_FIELDS=['location','timeOfDay','characters','emotionalBeat'];
const MIN_ACTION_SUMMARY_CHARS=40,VAGUE_LOCATION=/^(a |the )?(place|location|room|area|setting|somewhere|outside|inside)$/i;
const isStr=v=>typeof v==='string'&&v.trim().length>0,isObj=v=>v!==null&&typeof v==='object'&&!Array.isArray(v);
export function validateBeats(value){if(!Array.isArray(value)||!value.length)return{ok:false,errors:['beats must be a non-empty array']};const errors=[];value.forEach((b,i)=>{const p=`beats[${i}]`;if(!isObj(b))return errors.push(`${p} must be an object`);if(!isStr(b.verses))errors.push(`${p}.verses is required`);if(!isStr(b.summary))errors.push(`${p}.summary is required`);if(!Array.isArray(b.charactersMentioned))errors.push(`${p}.charactersMentioned must be an array`);if(typeof b.locationHint!=='string')errors.push(`${p}.locationHint must be a string`)});return{ok:!errors.length,errors}};
export function validateScene(s,path='scene'){if(!isObj(s))return[`${path} must be an object`];const e=[];if(!isStr(s.title))e.push(`${path}.title is required`);if(!isStr(s.verses))e.push(`${path}.verses is required`);if(!isObj(s.location))e.push(`${path}.location is required`);else{if(!isStr(s.location.name))e.push(`${path}.location.name is required`);else if(VAGUE_LOCATION.test(s.location.name.trim()))e.push(`${path}.location.name is too vague`);if(!SETTINGS.includes(s.location.setting))e.push(`${path}.location.setting must be one of ${SETTINGS.join('|')}`);if(!TIMES_OF_DAY.includes(s.location.timeOfDay))e.push(`${path}.location.timeOfDay must be one of ${TIMES_OF_DAY.join('|')}`)}if(!Array.isArray(s.characters)||!s.characters.length)e.push(`${path}.characters must be a non-empty array`);else s.characters.forEach((c,i)=>{const p=`${path}.characters[${i}]`;if(!isObj(c))return e.push(`${p} must be an object`);if(!isStr(c.name))e.push(`${p}.name is required`);if(!CHARACTER_ROLES.includes(c.role))e.push(`${p}.role must be one of ${CHARACTER_ROLES.join('|')}`);if(c.notes!==undefined&&typeof c.notes!=='string')e.push(`${p}.notes must be a string`)});if(!isObj(s.emotionalBeat))e.push(`${path}.emotionalBeat is required`);else{if(!isStr(s.emotionalBeat.primary))e.push(`${path}.emotionalBeat.primary is required`);if(!isStr(s.emotionalBeat.arc))e.push(`${path}.emotionalBeat.arc is required`)}if(!isStr(s.actionSummary)||s.actionSummary.trim().length<MIN_ACTION_SUMMARY_CHARS)e.push(`${path}.actionSummary must be at least ${MIN_ACTION_SUMMARY_CHARS} characters`);if(s.productionNotes!==undefined&&typeof s.productionNotes!=='string')e.push(`${path}.productionNotes must be a string`);if(!Array.isArray(s.inferredFields)||s.inferredFields.some(f=>!INFERABLE_FIELDS.includes(f)))e.push(`${path}.inferredFields is invalid`);return e}
export function validateScenes(value,{expectedCount}={}){if(!Array.isArray(value)||!value.length)return{ok:false,errors:['scenes must be a non-empty array']};const errors=[];if(expectedCount!==undefined&&value.length!==expectedCount)errors.push(`expected exactly ${expectedCount} scenes, got ${value.length}`);value.forEach((s,i)=>errors.push(...validateScene(s,`scenes[${i}]`)));return{ok:!errors.length,errors}};
