import crypto from "node:crypto";
import { getApexApp } from "./apex-six-apps.mjs";
const APP=getApexApp("ko-blocks");
const clone=value=>structuredClone(value);
const idOf=value=>{const id=String(value??"").trim();if(!/^[A-Za-z0-9][A-Za-z0-9._:/-]{0,255}$/.test(id))throw new TypeError("KoBlocks id is invalid");return id;};
export function defineKoBlock(input={}){const id=idOf(input.id||crypto.randomUUID());return{id,name:String(input.name||id),version:String(input.version||"1.0.0"),kind:String(input.kind||"component"),inputs:Array.isArray(input.inputs)?input.inputs.map(String):[],outputs:Array.isArray(input.outputs)?input.outputs.map(String):[],config:input.config&&typeof input.config==="object"?clone(input.config):{},provenance:input.provenance&&typeof input.provenance==="object"?clone(input.provenance):null};}
export function composeKoBlocks(blocks=[],edges=[]){const list=(Array.isArray(blocks)?blocks:[]).map(defineKoBlock),ids=new Set(list.map(b=>b.id));const links=(Array.isArray(edges)?edges:[]).map(edge=>{const from=idOf(edge.from),to=idOf(edge.to);if(!ids.has(from)||!ids.has(to))throw new Error("KoBlocks edge references an unknown block");return{from,to,port:edge.port?String(edge.port):null};});return{version:"koblx.v1",blocks:list,edges:links};}
export function validateKoBlockGraph(graph){if(!graph||!Array.isArray(graph.blocks)||!Array.isArray(graph.edges))throw new TypeError("KoBlocks graph is invalid");const ids=new Set(graph.blocks.map(b=>b.id));for(const edge of graph.edges){if(!ids.has(edge.from)||!ids.has(edge.to))return{valid:false,reason:"unknown-block"};if(edge.from===edge.to)return{valid:false,reason:"self-loop"};}return{valid:true,blockCount:graph.blocks.length,edgeCount:graph.edges.length};}
export function koBlocksStatus(){return{app:{...APP},role:APP.role,capabilities:["block registry","composition","graph validation","reusable components"],canonical:true,checkedAt:new Date().toISOString()};}
