import crypto from "node:crypto";
import { getApexApp } from "./apex-six-apps.mjs";
const APP=getApexApp("koin-kob");
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const uid=()=>crypto.randomUUID();
export function createWorkerAccount(input={}){return{workerId:String(input.workerId||uid()),balance:n(input.balance),reputation:n(input.reputation),skills:Array.isArray(input.skills)?input.skills.map(String):[],inventory:input.inventory&&typeof input.inventory==="object"?structuredClone(input.inventory):{},needs:Array.isArray(input.needs)?input.needs.map(String):[]};}
export function createMarketOrder(input={}){const side=String(input.side||"buy");if(!["buy","sell"].includes(side))throw new Error("Market order side must be buy or sell");const quantity=n(input.quantity),price=n(input.price);if(quantity<=0||price<0)throw new Error("Market order quantity/price is invalid");return{id:uid(),workerId:String(input.workerId||""),side,asset:String(input.asset||"service"),quantity,price,createdAt:new Date().toISOString()};}
export function clearMarket(orders=[]){const buys=(Array.isArray(orders)?orders:[]).filter(o=>o.side==="buy").map(o=>({...o})).sort((a,b)=>b.price-a.price),sells=(Array.isArray(orders)?orders:[]).filter(o=>o.side==="sell").map(o=>({...o})).sort((a,b)=>a.price-b.price),trades=[];let i=0,j=0;while(i<buys.length&&j<sells.length&&buys[i].price>=sells[j].price){const quantity=Math.min(buys[i].quantity,sells[j].quantity),price=(buys[i].price+sells[j].price)/2;trades.push({id:uid(),asset:buys[i].asset,quantity,price,buyer:buys[i].workerId,seller:sells[j].workerId,createdAt:new Date().toISOString()});buys[i].quantity-=quantity;sells[j].quantity-=quantity;if(buys[i].quantity<=0)i++;if(sells[j].quantity<=0)j++;}return{trades,unfilledBuys:buys.filter(o=>o.quantity>0),unfilledSells:sells.filter(o=>o.quantity>0)};}
export function createSystemicEvent(input={}){return{id:uid(),type:String(input.type||"resource-shortage"),severity:Math.max(0,Math.min(1,n(input.severity,.5))),target:String(input.target||"global"),payload:input.payload&&typeof input.payload==="object"?structuredClone(input.payload):{},createdAt:new Date().toISOString()};}
export function runAdversarialRound({workers=[],orders=[],events=[]}={}){const market=clearMarket(orders);return{roundId:uid(),workerCount:Array.isArray(workers)?workers.length:0,eventCount:Array.isArray(events)?events.length:0,trades:market.trades.length,volume:market.trades.reduce((s,t)=>s+t.quantity*t.price,0),unfilledBuys:market.unfilledBuys.length,unfilledSells:market.unfilledSells.length,generatedAt:new Date().toISOString()};}
export function koinKobStatus(){return{app:{...APP},role:APP.role,capabilities:["worker accounts","barter","market orders","market clearing","systemic events","adversarial rounds","economy-driven routing"],canonical:true,checkedAt:new Date().toISOString()};}
