import { sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core";
import { relations } from "drizzle-orm";

export const projects = sqliteTable("projects", { id: integer("id").primaryKey({autoIncrement:true}), title:text("title").notNull(), description:text("description"), primaryScripture:text("primary_scripture"), status:text("status").default("development"), createdAt:integer("created_at",{mode:"timestamp"}).$defaultFn(()=>new Date()), updatedAt:integer("updated_at",{mode:"timestamp"}).$defaultFn(()=>new Date()) });
export const characters = sqliteTable("characters", { id:integer("id").primaryKey({autoIncrement:true}), canonicalName:text("canonical_name").notNull(), aliases:text("aliases",{mode:"json"}).$type<string[]>().default([]), primaryStories:text("primary_stories",{mode:"json"}).$type<string[]>().default([]), relationships:text("relationships",{mode:"json"}).$type<{name:string;relation:string}[]>().default([]), keyTraits:text("key_traits",{mode:"json"}).$type<string[]>().default([]), notes:text("notes"), scriptureReferences:text("scripture_references",{mode:"json"}).$type<string[]>().default([]) });
export const scenes = sqliteTable("scenes", { id:integer("id").primaryKey({autoIncrement:true}), projectId:integer("project_id").references(()=>projects.id).notNull(), sceneNumber:integer("scene_number"), title:text("title"), scriptureRef:text("scripture_ref").notNull(), location:text("location"), charactersPresent:text("characters_present",{mode:"json"}).$type<number[]>().default([]), actionSummary:text("action_summary"), emotionalBeat:text("emotional_beat"), productionNotes:text("production_notes"), estimatedPages:real("estimated_pages"), dayOrNight:text("day_or_night") });
export const shootDays = sqliteTable("shoot_days", { id:integer("id").primaryKey({autoIncrement:true}), projectId:integer("project_id").references(()=>projects.id).notNull(), date:text("date").notNull(), unit:text("unit").default("1st Unit"), notes:text("notes") });
export const callSheets = sqliteTable("call_sheets", { id:integer("id").primaryKey({autoIncrement:true}), shootDayId:integer("shoot_day_id").references(()=>shootDays.id).notNull(), generalCallTime:text("general_call_time"), weatherNotes:text("weather_notes"), specialRequirements:text("special_requirements"), pdfPath:text("pdf_path"), createdAt:integer("created_at",{mode:"timestamp"}).$defaultFn(()=>new Date()) });
export const budgetItems = sqliteTable("budget_items", { id:integer("id").primaryKey({autoIncrement:true}), projectId:integer("project_id").references(()=>projects.id).notNull(), category:text("category").notNull(), description:text("description").notNull(), estimated:real("estimated").default(0), actual:real("actual").default(0), notes:text("notes") });
export const projectsRelations = relations(projects,({many})=>({scenes:many(scenes),shootDays:many(shootDays),budgetItems:many(budgetItems)}));
export const scenesRelations = relations(scenes,({one})=>({project:one(projects,{fields:[scenes.projectId],references:[projects.id]})}));
export const shootDaysRelations = relations(shootDays,({one,many})=>({project:one(projects,{fields:[shootDays.projectId],references:[projects.id]}),callSheets:many(callSheets)}));