from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="0001_initial"; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
 op.create_table("agencies",sa.Column("id",sa.Integer,primary_key=True),sa.Column("name",sa.String(300),nullable=False,unique=True),sa.Column("foia_portal_url",sa.String(1000)),sa.Column("contact_email",sa.String(320)),sa.Column("average_response_days",sa.Integer),sa.Column("exemption_categories",postgresql.ARRAY(sa.String)))
 op.create_table("users",sa.Column("id",sa.Integer,primary_key=True),sa.Column("email",sa.String(320),nullable=False,unique=True),sa.Column("password_hash",sa.String(255),nullable=False),sa.Column("role",sa.String(30),nullable=False),sa.Column("institutional_affiliation",sa.String(300)),sa.Column("is_active",sa.Boolean,nullable=False,server_default=sa.true()))
 op.create_table("foia_requests",sa.Column("id",sa.Integer,primary_key=True),sa.Column("tracking_number",sa.String(120),unique=True),sa.Column("agency_id",sa.Integer,sa.ForeignKey("agencies.id",ondelete="RESTRICT"),nullable=False),sa.Column("request_text",sa.Text,nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("date_submitted",sa.DateTime(timezone=True)),sa.Column("date_due",sa.DateTime(timezone=True)),sa.Column("date_completed",sa.DateTime(timezone=True)),sa.Column("appeal_status",sa.String(40)))
 op.create_index("idx_foia_requests_due","foia_requests",["date_due"]); op.create_index("idx_foia_requests_agency","foia_requests",["agency_id"])
 op.create_table("documents",sa.Column("id",sa.Integer,primary_key=True),sa.Column("request_id",sa.Integer,sa.ForeignKey("foia_requests.id",ondelete="SET NULL")),sa.Column("file_path",sa.String(1500)),sa.Column("file_hash",sa.String(128),nullable=False,unique=True),sa.Column("source_url",sa.String(2000)),sa.Column("classification_level",sa.String(40),nullable=False),sa.Column("redaction_count",sa.Integer,nullable=False,server_default="0"),sa.Column("ocr_text",sa.Text))
 op.create_table("sources",sa.Column("id",sa.Integer,primary_key=True),sa.Column("name",sa.String(300),nullable=False),sa.Column("type",sa.String(30),nullable=False),sa.Column("encrypted_contact_info",sa.Text),sa.Column("reliability_rating",sa.Integer),sa.Column("relationship_notes",sa.Text))
 op.create_table("investigations",sa.Column("id",sa.Integer,primary_key=True),sa.Column("title",sa.String(500),nullable=False),sa.Column("description",sa.Text),sa.Column("status",sa.String(40),nullable=False))
 op.create_table("investigation_requests",sa.Column("investigation_id",sa.Integer,sa.ForeignKey("investigations.id",ondelete="CASCADE"),primary_key=True),sa.Column("request_id",sa.Integer,sa.ForeignKey("foia_requests.id",ondelete="CASCADE"),primary_key=True))
 op.create_table("investigation_sources",sa.Column("investigation_id",sa.Integer,sa.ForeignKey("investigations.id",ondelete="CASCADE"),primary_key=True),sa.Column("source_id",sa.Integer,sa.ForeignKey("sources.id",ondelete="CASCADE"),primary_key=True))
 op.create_table("investigation_documents",sa.Column("investigation_id",sa.Integer,sa.ForeignKey("investigations.id",ondelete="CASCADE"),primary_key=True),sa.Column("document_id",sa.Integer,sa.ForeignKey("documents.id",ondelete="CASCADE"),primary_key=True))
 op.create_table("audit_logs",sa.Column("id",sa.Integer,primary_key=True),sa.Column("actor_user_id",sa.Integer,sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("action",sa.String(120),nullable=False),sa.Column("object_type",sa.String(80),nullable=False),sa.Column("object_id",sa.String(120),nullable=False),sa.Column("metadata_json",postgresql.JSONB),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()))
 op.create_index("idx_audit_logs_created_at","audit_logs",["created_at"])
def downgrade():
 for t in ["audit_logs","investigation_documents","investigation_sources","investigation_requests","investigations","sources","documents","foia_requests","users","agencies"]: op.drop_table(t)
