import {useEffect,useState} from "react";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
type NetworkState={status:string;verified:any;checkedAt:string;selected:any;failover:any[];candidates:any[];peers:any;speed:any;policy:any;planes?:any;error?:string};
type Benchmark={mib:number;bytes:number;elapsedMs:number;mbps:number;startedAt:string;finishedAt:string};
const stateLabel=(s:string)=>s==="connected"?"Connected":s==="degraded"?"Degraded":"Offline";
export default function NetworkDashboard(){const[data,setData]=useState<NetworkState|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[testing,setTesting]=useState(false);const[progress,setProgress]=useState(0);const[result,setResult]=useState<Benchmark|null>(null);
async function refresh(){try{setLoading(true);const r=await fetch("/api/network/status",{cache:"no-store"});if(!r.ok)throw new Error("Network telemetry unavailable");setData(await r.json());setError("")}catch(e){setError(e instanceof Error?e.message:"Network telemetry unavailable")}finally{setLoading(false)}}
async function runBenchmark(mib:number){if(testing)return;setTesting(true);setProgress(0);setResult(null);setError("");const startedAt=new Date().toISOString();const started=performance.now();try{const r=await fetch("/api/network/throughput?mib="+mib,{cache:"no-store"});if(!r.ok||!r.body)throw new Error("Throughput test unavailable (HTTP "+r.status+")");const total=Number(r.headers.get("x-apex-benchmark-bytes")||mib*1024*1024);const reader=r.body.getReader();let bytes=0;for(;;){const part=await reader.read();if(part.done)break;bytes+=part.value?.byteLength||0;setProgress(Math.min(100,(bytes/total)*100))}const elapsedMs=Math.max(1,performance.now()-started);setResult({mib,bytes,elapsedMs,mbps:(bytes*8)/(elapsedMs/1000)/1e6,startedAt,finishedAt:new Date().toISOString()});setProgress(100)}catch(e){setError(e instanceof Error?e.message:"Throughput test failed")}finally{setTesting(false)}}
useEffect(()=>{refresh();const id=window.setInterval(refresh,10000);return()=>window.clearInterval(id)},[]);
const selected=data?.selected;const peers=typeof data?.peers==="number"?data.peers:(data?.peers?.available===false?"Unavailable":"—");
return <div className="container mx-auto max-w-6xl p-6"><div className="mb-8 flex items-center justify-between"><div><h1 className="text-3xl font-bold tracking-tight">Apex Network</h1><p className="text-muted-foreground">Measured client connectivity</p></div><Button onClick={refresh} disabled={loading}>{loading?"Checking…":"Refresh"}</Button></div>
<Card><CardHeader><div className="flex items-center justify-between"><CardTitle>Connection</CardTitle><Badge>{data?stateLabel(data.status):"Detecting"}</Badge></div></CardHeader><CardContent><div className="grid gap-4 md:grid-cols-4"><div><div className="text-sm text-muted-foreground">Active path</div><b>{selected?.device||"None"}</b></div><div><div className="text-sm text-muted-foreground">Network</div><b>{selected?.network||"—"}</b></div><div><div className="text-sm text-muted-foreground">RTT</div><b>{Number.isFinite(selected?.rttMs)?Math.round(selected.rttMs)+" ms":"—"}</b></div><div><div className="text-sm text-muted-foreground">Peers</div><b>{peers}</b></div></div><div className="mt-6 rounded-lg border p-4"><div className="font-medium">{data?.speed?.mode==="multipath"?"Client multipath verified":data?.status==="connected"?"Single client path":"Network unavailable"}</div><p className="mt-1 text-sm text-muted-foreground">Only client-verified paths are presented as real iPhone network paths. Server runtime interfaces are diagnostic observations.</p><div className="mt-3 flex flex-wrap gap-2"><Badge>{data?.speed?.mode==="multipath"?"Multipath verified":"Multipath not verified"}</Badge><Badge>Failover {data?.failover?.length?"Ready":"Not verified"}</Badge><Badge>Adaptive telemetry</Badge><Badge>{data?.verified?.runtimeInterfacesObserved?"Server runtime observed":"Client telemetry"}</Badge></div></div>{error&&<p className="mt-4 text-sm text-destructive">{error}</p>}<p className="mt-4 text-xs text-muted-foreground">Last check: {data?.checkedAt?new Date(data.checkedAt).toLocaleString():"—"}</p></CardContent></Card>
<Card className="mt-6"><CardHeader><CardTitle>Real throughput test</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">Downloads a controlled payload from the live Apex deployment and measures the client-to-Apex transfer rate.</p><div className="mt-4 flex flex-wrap gap-3"><Button onClick={()=>runBenchmark(32)} disabled={testing}>Test 32 MiB</Button><Button onClick={()=>runBenchmark(64)} disabled={testing}>Test 64 MiB</Button></div>{testing&&<div className="mt-4"><div className="mb-2 flex justify-between text-sm"><span>Downloading…</span><span>{progress.toFixed(0)}%</span></div><div className="h-3 overflow-hidden rounded-full border"><div className="h-full transition-all" style={{width:progress+"%"}} /></div></div>}{result&&<div className="mt-4 grid gap-4 rounded-lg border p-4 md:grid-cols-4"><div><div className="text-sm text-muted-foreground">Throughput</div><b className="text-2xl">{result.mbps.toFixed(2)} Mbps</b></div><div><div className="text-sm text-muted-foreground">Payload</div><b>{(result.bytes/1024/1024).toFixed(1)} MiB</b></div><div><div className="text-sm text-muted-foreground">Elapsed</div><b>{(result.elapsedMs/1000).toFixed(2)} s</b></div><div><div className="text-sm text-muted-foreground">Status</div><Badge>Measured</Badge></div></div>}</CardContent></Card>
<Card className="mt-6"><CardHeader><CardTitle>Available paths</CardTitle></CardHeader><CardContent>{data?.candidates?.length?<div className="space-y-2">{data.candidates.map((p:any)=><div key={p.device} className="flex items-center justify-between rounded-md border p-3"><div><b>{p.device}</b><span className="ml-2 text-sm text-muted-foreground">{p.network}</span></div><div className="text-sm">{p.healthy?"Healthy":"Unavailable"} · {Number.isFinite(p.rttMs)?Math.round(p.rttMs)+" ms":"—"}</div></div>)}</div>:<p className="text-sm text-muted-foreground">No network interfaces are currently confirmed healthy.</p>}</CardContent></Card></div>}