import {useEffect,useState} from "react";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
type NetworkState={state:string;verified:boolean;checkedAt:string;selected:any;failover:any[];candidates:any[];peers:any;settings:any;error?:string};
const stateLabel=(s:string)=>s==="connected"?"Connected":s==="degraded"?"Degraded":"Offline";
export default function NetworkDashboard(){const[data,setData]=useState<NetworkState|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
async function refresh(){try{setLoading(true);const r=await fetch("/api/network/status",{cache:"no-store"});if(!r.ok)throw new Error("Network telemetry unavailable");setData(await r.json());setError("")}catch(e){setError(e instanceof Error?e.message:"Network telemetry unavailable")}finally{setLoading(false)}}
useEffect(()=>{refresh();const id=window.setInterval(refresh,10000);return()=>window.clearInterval(id)},[]);
const selected=data?.selected;const peers=typeof data?.peers==="number"?data.peers:(data?.peers?.available===false?"Unavailable":"—");
return <div className="container mx-auto max-w-6xl p-6"><div className="mb-8 flex items-center justify-between"><div><h1 className="text-3xl font-bold tracking-tight">Apex Network</h1><p className="text-muted-foreground">Live network fabric telemetry</p></div><Button onClick={refresh} disabled={loading}>{loading?"Checking…":"Refresh"}</Button></div>
<Card><CardHeader><div className="flex items-center justify-between"><CardTitle>Connection</CardTitle><Badge>{data?stateLabel(data.state):"Detecting"}</Badge></div></CardHeader><CardContent><div className="grid gap-4 md:grid-cols-4"><div><div className="text-sm text-muted-foreground">Active path</div><b>{selected?.device||"None"}</b></div><div><div className="text-sm text-muted-foreground">Network</div><b>{selected?.network||"—"}</b></div><div><div className="text-sm text-muted-foreground">RTT</div><b>{Number.isFinite(selected?.rttMs)?Math.round(selected.rttMs)+" ms":"—"}</b></div><div><div className="text-sm text-muted-foreground">Peers</div><b>{peers}</b></div></div><div className="mt-6 rounded-lg border p-4"><div className="font-medium">{data?.settings?.speed||"Maximum speed"}</div><p className="mt-1 text-sm text-muted-foreground">{data?.settings?.explanation||"Apex uses available capacity as conditions safely allow."}</p><div className="mt-3 flex flex-wrap gap-2"><Badge>Multipath {data?.settings?.multipleConnections||"On"}</Badge><Badge>Failover {data?.settings?.automaticFailover||"On"}</Badge><Badge>Adaptive {data?.settings?.automaticSpeedControl||"On"}</Badge><Badge>{data?.verified?"Runtime verified":"Telemetry only"}</Badge></div></div>{error&&<p className="mt-4 text-sm text-destructive">{error}</p>}<p className="mt-4 text-xs text-muted-foreground">Last check: {data?.checkedAt?new Date(data.checkedAt).toLocaleString():"—"}</p></CardContent></Card>
<Card className="mt-6"><CardHeader><CardTitle>Available paths</CardTitle></CardHeader><CardContent>{data?.candidates?.length?<div className="space-y-2">{data.candidates.map((p:any)=><div key={p.device} className="flex items-center justify-between rounded-md border p-3"><div><b>{p.device}</b><span className="ml-2 text-sm text-muted-foreground">{p.network}</span></div><div className="text-sm">{p.healthy?"Healthy":"Unavailable"} · {Number.isFinite(p.rttMs)?Math.round(p.rttMs)+" ms":"—"}</div></div>)}</div>:<p className="text-sm text-muted-foreground">No network interfaces are currently confirmed healthy.</p>}</CardContent></Card></div>}