import {useEffect,useState} from "react";
import {Button} from "@/components/ui/button"; import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card"; import {Badge} from "@/components/ui/badge"; import {Input} from "@/components/ui/input"; import {Textarea} from "@/components/ui/textarea"; import {Dialog,DialogContent,DialogHeader,DialogTitle} from "@/components/ui/dialog"; import {Plus,Pencil,Trash2} from "lucide-react"; import type {Project,ProjectOverview,ProjectStatus} from "@/types/project";
const statusColors:Record<ProjectStatus,string>={development:"bg-gray-500","pre-production":"bg-blue-500",production:"bg-green-500",post:"bg-purple-500"};
const label=(s:ProjectStatus)=>s==="pre-production"?"Pre-Production":s==="post"?"Post-Production":s[0].toUpperCase()+s.slice(1);
export default function ProjectDashboard(){const[projects,setProjects]=useState<ProjectOverview[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[editing,setEditing]=useState<Project|null>(null),[selected,setSelected]=useState<ProjectOverview|null>(null),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[scripture,setScripture]=useState(""),[status,setStatus]=useState<ProjectStatus>("development");
async function loadProjects(){setLoading(true);try{const r=await fetch("/api/projects");if(!r.ok)throw new Error("Unable to load projects");const data=await r.json();setProjects(data);if(selected)setSelected(data.find((p:ProjectOverview)=>p.id===selected.id)||null)}finally{setLoading(false)}}
useEffect(()=>{loadProjects()},[]);
function resetForm(){setTitle("");setDescription("");setScripture("");setStatus("development");setEditing(null)}
function openCreate(){resetForm();setOpen(true)}
function openEdit(p:Project){setEditing(p);setTitle(p.title);setDescription(p.description||"");setScripture(p.primaryScripture||"");setStatus(p.status);setOpen(true)}
async function handleSubmit(e:React.FormEvent){e.preventDefault();const payload={title,description,primaryScripture:scripture,status};await fetch(editing?`/api/projects/${editing.id}`:"/api/projects",{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});setOpen(false);resetForm();await loadProjects()}
async function handleDelete(id:number){if(!confirm("Delete this project?"))return;await fetch(`/api/projects/${id}`,{method:"DELETE"});if(selected?.id===id)setSelected(null);await loadProjects()}
if(loading)return <div className="p-8 text-center text-muted-foreground">Loading projects...</div>;
return <div className="container mx-auto max-w-6xl p-6"><div className="mb-8 flex items-center justify-between"><div><h1 className="text-3xl font-bold tracking-tight">Apex</h1><p className="text-muted-foreground">Bible Story Production</p></div><Button onClick={openCreate}><Plus className="mr-2 h-4 w-4"/>New Project</Button></div>
<Dialog open={open} onOpenChange={(v)=>{setOpen(v);if(!v)resetForm()}}><DialogContent><Card><CardHeader><DialogHeader><DialogTitle>{editing?"Edit Project":"Create New Project"}</DialogTitle></DialogHeader></CardHeader><CardContent><form onSubmit={handleSubmit} className="space-y-4"><label className="block text-sm font-medium">Title<Input value={title} onChange={e=>setTitle(e.target.value)} required placeholder="e.g. Exodus: The Red Sea"/></label><label className="block text-sm font-medium">Primary Scripture<Input value={scripture} onChange={e=>setScripture(e.target.value)} placeholder="e.g. Exodus 14:1-31"/></label><label className="block text-sm font-medium">Description<Textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Short summary of the production..."/></label><label className="block text-sm font-medium">Status<select className="mt-1 h-10 w-full rounded-md border px-3" value={status} onChange={e=>setStatus(e.target.value as ProjectStatus)}><option value="development">Development</option><option value="pre-production">Pre-Production</option><option value="production">Production</option><option value="post">Post-Production</option></select></label><Button type="submit" className="w-full">{editing?"Save Changes":"Create Project"}</Button></form></CardContent></Card></DialogContent></Dialog>
{projects.length===0?<Card><CardContent><div className="py-16 text-center"><h2 className="text-xl font-semibold">No projects yet</h2><p className="my-2 text-muted-foreground">Create your first Bible-story production to begin.</p><Button onClick={openCreate}><Plus className="mr-2 h-4 w-4"/>Create Project</Button></div></CardContent></Card>:<div className="grid gap-6 md:grid-cols-2">{projects.map(p=><Card key={p.id} className="cursor-pointer" onClick={()=>setSelected(p)}><CardHeader><div className="flex items-start justify-between gap-3"><CardTitle>{p.title}</CardTitle><Badge className={statusColors[p.status]}>{label(p.status)}</Badge></div><p className="text-sm text-muted-foreground">{p.primaryScripture||"Primary scripture not set"}</p></CardHeader><CardContent><div className="grid grid-cols-3 gap-3 text-sm"><div><div className="text-muted-foreground">Scenes</div><b>{p.sceneCount}</b></div><div><div className="text-muted-foreground">Characters</div><b>{p.characterCount}</b></div><div><div className="text-muted-foreground">Next shoot</div><b>{p.nextShootDay||"None"}</b></div></div><div className="mt-5 flex gap-2"><Button onClick={e=>{e.stopPropagation();openEdit(p)}}><Pencil className="mr-2 h-4 w-4"/>Edit</Button><Button className="bg-red-600 hover:bg-red-700" onClick={e=>{e.stopPropagation();handleDelete(p.id)}}><Trash2 className="mr-2 h-4 w-4"/>Delete</Button></div></CardContent></Card>)}</div>}
{selected&&<Card className="mt-6"><CardHeader><CardTitle>Project Overview: {selected.title}</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">{selected.primaryScripture||"Primary scripture not set"}</p><div className="mt-4 grid gap-4 md:grid-cols-3"><div><b>Scenes</b><div>{selected.sceneCount}</div></div><div><b>Linked characters</b><div>{selected.characterCount}</div></div><div><b>Next shoot day</b><div>{selected.nextShootDay||"None scheduled"}</div></div></div></CardContent></Card>}</div>}