import express from "express";
import { exportStudio, importStudio } from "../core/import-export.mjs";
import { evaluateArtifact } from "../core/evaluation.mjs";
export function createApi(studio){
 const r=express.Router();
 const requireLayers=(req,res,next)=>{
  try{ studio.mature.requireUnlocked(req.get("x-layers-token")); next(); }
  catch(e){ res.status(403).json({error:"Layers locked"}); }
 };
 r.get("/health",(req,res)=>res.json({ok:true,name:"Apex Studio",version:studio.version,time:new Date().toISOString(),mode:studio.localMode.isOffline()?"offline":"network-enabled"}));
 r.get("/snapshot",(req,res)=>res.json(studio.snapshot()));
 r.get("/privacy",(req,res)=>res.json(studio.privacy));
 r.get("/search",(req,res)=>res.json(studio.search(req.query.q??"",Number(req.query.limit??30))));
 r.get("/metrics",(req,res)=>res.json(studio.metrics.snapshot()));
 r.get("/universe",(req,res)=>res.json(studio.universe.list()));
 r.get("/projects",(req,res)=>res.json(studio.projects.list()));
 r.post("/projects",(req,res)=>res.status(201).json(studio.projects.create(req.body??{})));
 r.get("/memory",(req,res)=>res.json(studio.memory.search(req.query.q??"",{projectId:req.query.projectId})));
 r.post("/memory",(req,res)=>res.status(201).json(studio.memory.remember(req.body??{})));
 r.get("/characters",(req,res)=>res.json(studio.characters.list()));
 r.post("/characters",(req,res)=>res.status(201).json(studio.characters.create(req.body??{})));
 r.get("/sources",(req,res)=>res.json(studio.sources.list()));
 r.post("/sources",(req,res)=>res.status(201).json(studio.sources.add(req.body??{})));
 r.get("/documents",(req,res)=>res.json(studio.knowledgeBase.list()));
 r.post("/documents",(req,res)=>res.status(201).json(studio.knowledgeBase.addDocument(req.body??{})));
 r.post("/documents/:id/chunk",(req,res)=>res.json(studio.knowledgeBase.chunk(req.params.id,Number(req.body?.size??1200))));
 r.get("/documents/search",(req,res)=>res.json(studio.knowledgeBase.search(req.query.q??"",Number(req.query.limit??20))));
 r.get("/renders",(req,res)=>res.json(studio.render.list()));
 r.post("/renders",(req,res)=>res.status(202).json(studio.render.enqueue(req.body??{})));
 r.get("/releases",(req,res)=>res.json(studio.releases.list()));
 r.post("/releases",(req,res)=>res.status(201).json(studio.releases.create(req.body??{})));
 r.post("/releases/:id/publish",(req,res)=>res.json(studio.releases.publish(req.params.id)));
 r.get("/collaboration",(req,res)=>res.json(studio.collaboration.list()));
 r.post("/collaboration",(req,res)=>res.status(201).json(studio.collaboration.append(req.body??{})));
 r.post("/assets",(req,res)=>{const a=studio.assets.create(req.body??{});studio.events.emit("asset.created",a);res.status(201).json(a)});
 r.get("/scenes",(req,res)=>res.json(studio.listScenes()));
 r.post("/scenes",(req,res)=>res.status(201).json(studio.createScene(req.body??{})));
 r.get("/jobs",(req,res)=>res.json(studio.jobs.list()));
 r.post("/jobs",(req,res)=>res.status(202).json(studio.jobs.enqueue(req.body?.type,req.body?.payload,req.body)));
 r.post("/jobs/:id/run",async(req,res)=>res.json(await studio.jobs.run(req.params.id)));
 r.get("/tools",(req,res)=>res.json(studio.tools.describe()));
 r.get("/realism/status",(req,res)=>res.json({profiles:studio.realism.list().length}));
 r.get("/adaptive-intimacy/status",(req,res)=>res.json({profiles:studio.adaptiveIntimacy.list().length,sessions:[...studio.adaptiveIntimacy.sessions.values()].length}));
 r.get("/layers/status",(req,res)=>res.json(studio.mature.layerStatus()));
 r.post("/layers/runtime/open",(req,res)=>{try{res.status(201).json(studio.matureRuntime.open({...(req.body??{}),token:req.get("x-layers-token")}))}catch(e){res.status(403).json({error:e.message})}});
 r.post("/layers/runtime/:id/close",(req,res)=>{try{res.json(studio.matureRuntime.close(req.params.id,req.get("x-layers-token")))}catch(e){res.status(403).json({error:e.message})}});
 r.get("/layers/runtime",(req,res)=>{try{res.json(studio.matureRuntime.list(req.get("x-layers-token")))}catch(e){res.status(403).json({error:e.message})}});

 r.post("/layers/unlock",(req,res)=>res.json(studio.mature.unlock(req.body?.passcode,req.body?.ttlMs)));
 r.post("/layers/lock",(req,res)=>res.json(studio.mature.lock(req.body?.token)));
 r.get("/layers/mature",(req,res)=>{try{studio.mature.requireUnlocked(req.get("x-layers-token"));res.json(studio.mature.status())}catch(e){res.status(403).json({error:"Layers locked"})}});
 r.use("/mature",requireLayers);
 r.use("/companions",requireLayers);
 r.get("/mature/status",(req,res)=>res.json(studio.mature.status()));
 r.get("/mature/categories",(req,res)=>res.json({categories:studio.mature.status().categories}));
 r.post("/mature/policy",(req,res)=>res.json(studio.mature.updatePolicy(req.body??{})));
 r.post("/mature/category",(req,res)=>res.json(studio.mature.setCategory(req.body?.category,req.body?.enabled)));
 r.post("/mature/media",(req,res)=>res.json(studio.mature.setMediaType(req.body?.mediaType,req.body?.enabled)));
 r.post("/mature/projects",(req,res)=>res.status(201).json(studio.mature.setProject(req.body??{})));
 r.get("/mature/audit",(req,res)=>res.json(studio.mature.listAudit()));
 r.get("/intimacy",(req,res)=>res.json(studio.intimacy.list()));
 r.post("/intimacy",(req,res)=>res.status(201).json(studio.intimacy.create(req.body??{})));
 r.post("/intimacy/:id",(req,res)=>res.json(studio.intimacy.update(req.params.id,req.body??{})));
 r.post("/intimacy/:id/moments",(req,res)=>res.status(201).json(studio.intimacy.addMoment(req.params.id,req.body??{})));
 r.get("/intimacy/:id/moments",(req,res)=>res.json(studio.intimacy.momentsFor(req.params.id)));
 r.post("/intimacy/:id/date-nights",(req,res)=>res.status(201).json(studio.intimacy.startDateNight(req.params.id,req.body??{})));
 r.post("/intimacy/date-nights/:id/end",(req,res)=>res.json(studio.intimacy.endDateNight(req.params.id)));
 r.get("/adaptive-intimacy",(req,res)=>res.json(studio.adaptiveIntimacy.list()));
 r.post("/adaptive-intimacy",(req,res)=>res.status(201).json(studio.adaptiveIntimacy.create(req.body??{})));
 r.get("/adaptive-intimacy/:id",(req,res)=>res.json(studio.adaptiveIntimacy.get(req.params.id)));
 r.post("/adaptive-intimacy/:id",(req,res)=>res.json(studio.adaptiveIntimacy.update(req.params.id,req.body??{})));
 r.post("/adaptive-intimacy/:id/boundaries",(req,res)=>res.json(studio.adaptiveIntimacy.setBoundary(req.params.id,req.body?.key,req.body?.value)));
 r.post("/adaptive-intimacy/:id/transition",(req,res)=>res.json(studio.adaptiveIntimacy.transition(req.params.id,req.body?.level,{consent:req.body?.consent,reason:req.body?.reason??"user-request"})));
 r.post("/adaptive-intimacy/:id/signals",(req,res)=>res.json(studio.adaptiveIntimacy.recordSignal(req.params.id,req.body?.signal,req.body?.value)));
 r.post("/adaptive-intimacy/:id/preferences",(req,res)=>res.json(studio.adaptiveIntimacy.setPreference(req.params.id,req.body?.key,req.body?.value)));
 r.post("/adaptive-intimacy/:id/evaluate",(req,res)=>res.json(studio.adaptiveIntimacy.evaluate(req.params.id,{requestedLevel:req.body?.level??null,consent:req.body?.consent===true})));
 r.post("/adaptive-intimacy/:id/sessions",(req,res)=>res.status(201).json(studio.adaptiveIntimacy.startSession(req.params.id,req.body?.media??"chat")));
 r.get("/adaptive-intimacy/:id/sessions",(req,res)=>res.json(studio.adaptiveIntimacy.session(req.params.id)));
 r.post("/adaptive-intimacy/sessions/:id/pause",(req,res)=>res.json(studio.adaptiveIntimacy.pauseSession(req.params.id)));
 r.post("/adaptive-intimacy/sessions/:id/resume",(req,res)=>res.json(studio.adaptiveIntimacy.resumeSession(req.params.id)));
 r.post("/adaptive-intimacy/sessions/:id/end",(req,res)=>res.json(studio.adaptiveIntimacy.endSession(req.params.id)));
 r.get("/adaptive-intimacy/:id/events",(req,res)=>res.json(studio.adaptiveIntimacy.eventsFor(req.params.id)));
 r.get("/realism",(req,res)=>res.json(studio.realism.list()));
 r.post("/realism",(req,res)=>res.status(201).json(studio.realism.create(req.body??{})));
 r.get("/realism/:id",(req,res)=>res.json(studio.realism.get(req.params.id)));
 r.post("/realism/:id",(req,res)=>res.json(studio.realism.update(req.params.id,req.body??{})));
 r.post("/realism/:id/prompt",(req,res)=>res.json(studio.realism.promptSpec(req.params.id)));
 r.get("/presence",(req,res)=>res.json(studio.presence.list()));
 r.post("/presence",(req,res)=>res.status(201).json(studio.presence.create(req.body??{})));
 r.post("/presence/:id",(req,res)=>res.json(studio.presence.update(req.params.id,req.body??{})));
 r.post("/presence/:id/start",(req,res)=>res.status(201).json(studio.presence.start(req.params.id,req.body?.media??"chat")));
 r.post("/presence/sessions/:id/stop",(req,res)=>res.json(studio.presence.stop(req.params.id)));
 r.get("/companions",(req,res)=>res.json(studio.companions.list()));
 r.post("/companions",(req,res)=>res.status(201).json(studio.companions.create(req.body??{})));
 r.get("/companions/:id",(req,res)=>res.json(studio.companions.get(req.params.id)));
 r.post("/companions/:id/media",(req,res)=>res.json(studio.companions.setMedia(req.params.id,req.body?.media,req.body?.enabled)));
 r.post("/companions/:id/preferences",(req,res)=>res.json(studio.companions.setPreference(req.params.id,req.body?.key,req.body?.value)));
 r.post("/companions/:id/boundaries",(req,res)=>res.json(studio.companions.setBoundary(req.params.id,req.body?.key,req.body?.value)));
 r.post("/companions/:id/relationship",(req,res)=>res.json(studio.companions.updateRelationship(req.params.id,req.body??{})));
 r.post("/companions/:id/memories",(req,res)=>res.status(201).json(studio.companions.remember(req.params.id,req.body??{})));
 r.get("/companions/:id/memories",(req,res)=>res.json(studio.companions.memories(req.params.id)));
 r.post("/companions/:id/sessions",(req,res)=>res.status(201).json(studio.companions.startSession(req.params.id,req.body?.media??"chat")));
 r.post("/companions/sessions/:id/end",(req,res)=>res.json(studio.companions.endSession(req.params.id)));
 r.get("/companions/sessions/:id/messages",(req,res)=>res.json(studio.companions.listMessages(req.params.id)));
 r.post("/companions/sessions/:id/messages",(req,res)=>res.status(201).json(studio.companions.addMessage(req.params.id,req.body??{})));
 r.get("/providers",(req,res)=>res.json(studio.providers.names()));
 r.post("/command",async(req,res)=>{try{res.json(await studio.command(req.body?.name,req.body?.args??{}))}catch(e){res.status(400).json({error:e.message})}});
 r.post("/evaluate",(req,res)=>res.json(evaluateArtifact(req.body?.artifact,{requiredFields:req.body?.requiredFields??[],provenance:req.body?.provenance??[],continuity:req.body?.continuity??[]})));
 r.get("/export",(req,res)=>res.json(exportStudio(studio)));
 r.post("/import",(req,res)=>{try{res.json(importStudio(studio,req.body))}catch(e){res.status(400).json({error:e.message})}});
 return r;
}