import express from "express";
import { exportStudio, importStudio } from "../core/import-export.mjs";
import { evaluateArtifact } from "../core/evaluation.mjs";
export function createApi(studio){
 const r=express.Router();
 r.get("/health",(req,res)=>res.json({ok:true,name:"Apex Studio",version:studio.version,time:new Date().toISOString(),mode:studio.localMode.isOffline()?"offline":"network-enabled"}));
 r.get("/snapshot",(req,res)=>res.json(studio.snapshot()));
 r.get("/privacy",(req,res)=>res.json(studio.privacy));
 r.get("/search",(req,res)=>res.json(studio.search(req.query.q??"",Number(req.query.limit??30))));
 r.get("/metrics",(req,res)=>res.json(studio.metrics.snapshot()));
 r.get("/universe",(req,res)=>res.json(studio.universe.list()));
 r.get("/projects",(req,res)=>res.json(studio.projects.list()));
 r.post("/projects",(req,res)=>res.status(201).json(studio.projects.create(req.body??{})));
 r.get("/memory",(req,res)=>res.json(studio.memory.search(req.query.q??"",{projectId:req.query.projectId})));
 r.post("/memory",(req,res)=>res.status(201).json(studio.memory.remember(req.body??{})));
 r.get("/characters",(req,res)=>res.json(studio.characters.list()));
 r.post("/characters",(req,res)=>res.status(201).json(studio.characters.create(req.body??{})));
 r.get("/sources",(req,res)=>res.json(studio.sources.list()));
 r.post("/sources",(req,res)=>res.status(201).json(studio.sources.add(req.body??{})));
 r.get("/documents",(req,res)=>res.json(studio.knowledgeBase.list()));
 r.post("/documents",(req,res)=>res.status(201).json(studio.knowledgeBase.addDocument(req.body??{})));
 r.post("/documents/:id/chunk",(req,res)=>res.json(studio.knowledgeBase.chunk(req.params.id,Number(req.body?.size??1200))));
 r.get("/documents/search",(req,res)=>res.json(studio.knowledgeBase.search(req.query.q??"",Number(req.query.limit??20))));
 r.get("/renders",(req,res)=>res.json(studio.render.list()));
 r.post("/renders",(req,res)=>res.status(202).json(studio.render.enqueue(req.body??{})));
 r.get("/releases",(req,res)=>res.json(studio.releases.list()));
 r.post("/releases",(req,res)=>res.status(201).json(studio.releases.create(req.body??{})));
 r.post("/releases/:id/publish",(req,res)=>res.json(studio.releases.publish(req.params.id)));
 r.get("/collaboration",(req,res)=>res.json(studio.collaboration.list()));
 r.post("/collaboration",(req,res)=>res.status(201).json(studio.collaboration.append(req.body??{})));
 r.post("/assets",(req,res)=>{const a=studio.assets.create(req.body??{});studio.events.emit("asset.created",a);res.status(201).json(a)});
 r.get("/scenes",(req,res)=>res.json(studio.listScenes()));
 r.post("/scenes",(req,res)=>res.status(201).json(studio.createScene(req.body??{})));
 r.get("/jobs",(req,res)=>res.json(studio.jobs.list()));
 r.post("/jobs",(req,res)=>res.status(202).json(studio.jobs.enqueue(req.body?.type,req.body?.payload,req.body)));
 r.post("/jobs/:id/run",async(req,res)=>res.json(await studio.jobs.run(req.params.id)));
 r.get("/tools",(req,res)=>res.json(studio.tools.describe()));
 r.get("/mature/status",(req,res)=>res.json(studio.mature.status()));
 r.get("/mature/categories",(req,res)=>res.json({categories:studio.mature.status().categories}));
 r.post("/mature/policy",(req,res)=>res.json(studio.mature.updatePolicy(req.body??{})));
 r.post("/mature/category",(req,res)=>res.json(studio.mature.setCategory(req.body?.category,req.body?.enabled)));
 r.post("/mature/media",(req,res)=>res.json(studio.mature.setMediaType(req.body?.mediaType,req.body?.enabled)));
 r.post("/mature/projects",(req,res)=>res.status(201).json(studio.mature.setProject(req.body??{})));
 r.get("/mature/audit",(req,res)=>res.json(studio.mature.listAudit()));
 r.get("/companions",(req,res)=>res.json(studio.companions.list()));
 r.post("/companions",(req,res)=>res.status(201).json(studio.companions.create(req.body??{})));
 r.get("/companions/:id",(req,res)=>res.json(studio.companions.get(req.params.id)));
 r.post("/companions/:id/media",(req,res)=>res.json(studio.companions.setMedia(req.params.id,req.body?.media,req.body?.enabled)));\n r.post("/companions/:id/preferences",(req,res)=>res.json(studio.companions.setPreference(req.params.id,req.body?.key,req.body?.value)));\n r.post("/companions/:id/boundaries",(req,res)=>res.json(studio.companions.setBoundary(req.params.id,req.body?.key,req.body?.value)));\n r.post("/companions/:id/relationship",(req,res)=>res.json(studio.companions.updateRelationship(req.params.id,req.body??{})));\n r.post("/companions/:id/memories",(req,res)=>res.status(201).json(studio.companions.remember(req.params.id,req.body??{})));\n r.get("/companions/:id/memories",(req,res)=>res.json(studio.companions.memories(req.params.id)));
 r.post("/companions/:id/sessions",(req,res)=>res.status(201).json(studio.companions.startSession(req.params.id,req.body?.media??"chat")));
 r.post("/companions/sessions/:id/end",(req,res)=>res.json(studio.companions.endSession(req.params.id)));\n r.get("/companions/sessions/:id/messages",(req,res)=>res.json(studio.companions.listMessages(req.params.id)));\n r.post("/companions/sessions/:id/messages",(req,res)=>res.status(201).json(studio.companions.addMessage(req.params.id,req.body??{})));
 r.get("/providers",(req,res)=>res.json(studio.providers.names()));
 r.post("/command",async(req,res)=>{try{res.json(await studio.command(req.body?.name,req.body?.args??{}))}catch(e){res.status(400).json({error:e.message})}});
 r.post("/evaluate",(req,res)=>res.json(evaluateArtifact(req.body?.artifact,{requiredFields:req.body?.requiredFields??[],provenance:req.body?.provenance??[],continuity:req.body?.continuity??[]})));
 r.get("/export",(req,res)=>res.json(exportStudio(studio)));
 r.post("/import",(req,res)=>{try{res.json(importStudio(studio,req.body))}catch(e){res.status(400).json({error:e.message})}});
 return r;
}