import { listCollection,getCollection,createCollection,putCollection,deleteCollection } from "./apex-data.mjs";
import { autoSchedule,buildCalendar } from "../schedule/rules.js";
const mapDay=r=>({id:r.id,projectId:r.projectId,shootDate:r.date,callTime:r.callTime??null,notes:r.notes??""});
const mapScene=r=>({...r,sequence:r.sceneNumber??r.id,location:{name:r.location??"",timeOfDay:r.dayOrNight||"UNSPECIFIED"}});
export async function createShootDay({projectId,shootDate,callTime=null,notes=""}){if(!(await getCollection("projects",projectId)))return null;const days=await listCollection("shoot_days");if(days.some(x=>Number(x.projectId)===Number(projectId)&&x.date===shootDate))throw Object.assign(new Error("A shoot day already exists for this project and date"),{code:"DUPLICATE_DATE"});return mapDay(await createCollection("shoot_days",{projectId:Number(projectId),date:shootDate,callTime,notes,unit:"1st Unit"}));}
export const deleteShootDay=id=>deleteCollection("shoot_days",id);
export async function getDay(id){const x=await getCollection("shoot_days",id);return x?mapDay(x):null;}
export async function listDays(projectId){return(await listCollection("shoot_days")).filter(x=>Number(x.projectId)===Number(projectId)).sort((a,b)=>String(a.date).localeCompare(String(b.date))).map(mapDay);}
export async function listAssignments(projectId){const days=(await listCollection("shoot_days")).filter(x=>Number(x.projectId)===Number(projectId));const ids=new Set(days.map(x=>Number(x.id)));return(await listCollection("shoot_day_scenes")).filter(x=>ids.has(Number(x.shootDayId))).sort((a,b)=>(Number(a.position)||0)-(Number(b.position)||0)).map(x=>({sceneId:x.sceneId,shootDayId:x.shootDayId,position:x.position}));}
export async function listScenesForProject(projectId){return(await listCollection("scenes")).filter(x=>Number(x.projectId)===Number(projectId)).sort((a,b)=>(Number(a.sceneNumber)||0)-(Number(b.sceneNumber)||0)||Number(a.id)-Number(b.id)).map(mapScene);}
export async function assignScenes(shootDayId,sceneIds){const day=await getDay(shootDayId);if(!day)throw Object.assign(new Error("Shoot day not found"),{code:"NOT_FOUND"});const ids=[...new Set(sceneIds.map(Number))],scenes=await listCollection("scenes");if(ids.some(id=>!scenes.some(x=>Number(x.id)===id&&Number(x.projectId)===Number(day.projectId))))throw Object.assign(new Error("All scenes must belong to the same project as the shoot day"),{code:"PROJECT_SCOPE"});for(const row of(await listCollection("shoot_day_scenes")).filter(x=>Number(x.shootDayId)===Number(shootDayId)||ids.includes(Number(x.sceneId))))await deleteCollection("shoot_day_scenes",row.id);for(const [position,sceneId] of ids.entries())await createCollection("shoot_day_scenes",{sceneId,shootDayId:Number(shootDayId),position});return listAssignments(day.projectId);}
export async function unassignScene(sceneId){let changed=false;for(const row of(await listCollection("shoot_day_scenes")).filter(x=>Number(x.sceneId)===Number(sceneId)))changed=(await deleteCollection("shoot_day_scenes",row.id))||changed;return changed;}
export async function reorderDay(shootDayId,sceneIds){const day=await getDay(shootDayId);if(!day)throw Object.assign(new Error("Shoot day not found"),{code:"NOT_FOUND"});const rows=(await listCollection("shoot_day_scenes")).filter(x=>Number(x.shootDayId)===Number(shootDayId)),ids=sceneIds.map(Number);if(rows.length!==ids.length||rows.some(x=>!ids.includes(Number(x.sceneId))))throw Object.assign(new Error("Order must contain exactly the scenes assigned to this day"),{code:"INVALID_ORDER"});for(const [position,id] of ids.entries()){const row=rows.find(x=>Number(x.sceneId)===id);await putCollection("shoot_day_scenes",row.id,{...row,position});}return listAssignments(day.projectId);}
export async function getCalendar(projectId,options){return buildCalendar({days:await listDays(projectId),assignments:await listAssignments(projectId),scenes:await listScenesForProject(projectId),options});}
export async function runAutoSchedule(projectId,options){const scenes=await listScenesForProject(projectId),assignments=await listAssignments(projectId),assigned=new Set(assignments.map(x=>x.sceneId)),days=await listDays(projectId),result=autoSchedule(scenes.filter(x=>!assigned.has(x.id)),days.map(d=>({...d,existingCount:assignments.filter(x=>x.shootDayId===d.id).length})),options);for(const item of result.plan)await assignScenes(item.dayId,item.sceneIds);return{...(await getCalendar(projectId,options)),overflow:result.overflow};}
