import { apexPureDataStore as store } from "../core/apex-pure-data.mjs";
import { autoSchedule, buildCalendar } from "../schedule/rules.js";

export type ScheduleOptions={maxScenes?:number};
export type ShootDayInput={projectId:number;shootDate:string;callTime?:string|null;notes?:string};

const mapDay=(r:any)=>({id:r.id,projectId:r.projectId,shootDate:r.date,callTime:r.callTime??null,notes:r.notes??""});
const mapScene=(r:any)=>({...r,sequence:r.sceneNumber??r.id,location:{name:r.location??"",timeOfDay:r.dayOrNight||"UNSPECIFIED"}});

export async function createShootDay({projectId,shootDate,callTime=null,notes=""}:ShootDayInput){
  if(!(await store.get("projects",String(projectId))))return null;
  if((await store.query("shootDays",x=>Number(x.projectId)===projectId&&String(x.date)===shootDate)).length)throw Object.assign(new Error("A shoot day already exists for this project and date"),{code:"DUPLICATE_DATE"});
  return mapDay(await store.create("shootDays",{projectId,date:shootDate,callTime,notes,unit:"1st Unit"}));
}
export async function deleteShootDay(id:number){if(!(await store.get("shootDays",String(id))))return false;for(const x of await store.query("shootDayScenes",a=>Number(a.shootDayId)===id))await store.delete("shootDayScenes",x.id);await store.delete("shootDays",String(id));return true;}
export async function getDay(id:number){const x=await store.get("shootDays",String(id));return x?mapDay(x):null;}
export async function listDays(projectId:number){return(await store.query("shootDays",x=>Number(x.projectId)===projectId,{sort:(a,b)=>String(a.date).localeCompare(String(b.date))})).map(mapDay);}
export async function listAssignments(projectId:number){const days=await store.query("shootDays",x=>Number(x.projectId)===projectId);const ids=new Set(days.map(x=>String(x.id)));return(await store.query("shootDayScenes",x=>ids.has(String(x.shootDayId)),{sort:(a,b)=>Number(a.position)-Number(b.position)})).map(x=>({sceneId:Number(x.sceneId),shootDayId:Number(x.shootDayId),position:Number(x.position)}));}
export async function listScenesForProject(projectId:number){return(await store.query("scenes",x=>Number(x.projectId)===projectId,{sort:(a,b)=>Number(a.sceneNumber??0)-Number(b.sceneNumber??0)})).map(mapScene);}
export async function assignScenes(shootDayId:number,sceneIds:unknown[]){const d=await getDay(shootDayId);if(!d)throw Object.assign(new Error("Shoot day not found"),{code:"NOT_FOUND"});const unique=[...new Set(sceneIds.map(Number))];const valid=(await store.query("scenes",x=>Number(x.projectId)===Number(d.projectId)&&unique.includes(Number(x.id)))).map(x=>Number(x.id));if(unique.some(x=>!valid.includes(x)))throw Object.assign(new Error("All scenes must belong to the same project as the shoot day"),{code:"PROJECT_SCOPE"});for(const row of await store.query("shootDayScenes",x=>Number(x.shootDayId)===shootDayId))await store.delete("shootDayScenes",row.id);for(const row of await store.query("shootDayScenes",x=>unique.includes(Number(x.sceneId))))await store.delete("shootDayScenes",row.id);for(const [position,sceneId] of unique.entries())await store.put("shootDayScenes",String(sceneId),{id:sceneId,sceneId,shootDayId,position});return listAssignments(d.projectId);}
export async function unassignScene(sceneId:number){const rows=await store.query("shootDayScenes",x=>Number(x.sceneId)===sceneId);for(const row of rows)await store.delete("shootDayScenes",row.id);return rows.length>0;}
export async function reorderDay(shootDayId:number,sceneIds:unknown[]){const d=await getDay(shootDayId);if(!d)throw Object.assign(new Error("Shoot day not found"),{code:"NOT_FOUND"});const unique=[...new Set(sceneIds.map(Number))];const assigned=(await store.query("shootDayScenes",x=>Number(x.shootDayId)===shootDayId)).map(x=>Number(x.sceneId));if(assigned.length!==unique.length||assigned.some(x=>!unique.includes(x)))throw Object.assign(new Error("Order must contain exactly the scenes assigned to this day"),{code:"INVALID_ORDER"});for(const [position,sceneId] of unique.entries()){const row=await store.get("shootDayScenes",String(sceneId));if(row)await store.put("shootDayScenes",String(sceneId),{...row,position});}return listAssignments(d.projectId);}
export async function getCalendar(projectId:number,options?:ScheduleOptions){return buildCalendar({days:await listDays(projectId),assignments:await listAssignments(projectId),scenes:await listScenesForProject(projectId),options});}
export async function runAutoSchedule(projectId:number,options?:ScheduleOptions){const all=await listScenesForProject(projectId),assignments=await listAssignments(projectId),assigned=new Set(assignments.map(a=>a.sceneId)),days=await listDays(projectId);const result=autoSchedule(all.filter(s=>!assigned.has(s.id)),days.map(d=>({...d,existingCount:assignments.filter(a=>a.shootDayId===d.id).length})),options);for(const item of result.plan)await assignScenes(item.dayId,item.sceneIds);return{...(await getCalendar(projectId,options)),overflow:result.overflow};}
